### ISSUE TITLE
Setting up voices in init causes react component to rerender

### ISSUE THREAD

**Issue by jhe01** [tom-s/speak-tts#15] opened 2019-03-09 05:05 UTC
Hello,

I set voice in init function. when speak has been executed it causes my component to rerender 2 to 3 times or more than that causes improper execution of function in my component.

But when i did not set the voice, it works properly. I need to set so probably I need help. because my local and my production has different default voice that is selected when speaking. my local uses Zira voice but my production uses David or something male voice though they are same windows OS and chrome browser.

i am using 

reactjs v16.8.3
speak-tts v2.0.8

Thanks in advance for the help

**Comment by tom-s** [comment] 2019-03-09 10:21
Hi,
Can you please provide code that allows to reproduce the issue ? It seems to be to be related to your implementation in react rather than the library itself.

**Comment by jhe01** [comment] 2019-03-10 05:05
Hello,

I have a queue table. That table compose of times that have interval of 20 mins from start all the way to the end that of the time that I set but every time in the table have 4 sets on it. (ex. (10:00 A, 10:00 B, 10:00 C, 10:00 D) from 10 AM to 5 PM). Every time it reach the interval it would announce A then after a minute B then after a minute C then after a minute D.

This is how I set my speak.

![image](https://user-images.githubusercontent.com/35474475/54080194-87a37c00-4325-11e9-88fe-e24ebcc1ff83.png)

Now in my Table Row Component

```
import React, { Component } from "react";
import moment from "moment";
import InitSound from "./InitSound";

import {
  generateClassNamePerRow,
  get12hrsValue,
  compareTime
} from "../util/util";
import { announce } from "../util/speak";

class TableRows extends Component {
  state = {
    isHidden: false,
    toAnnounce: false,
    row: {},
    interval: 20 //change this to test out
  };

  handleStartTimer = () => {
    const { time } = this.props.row;
    if (!this.timer && !compareTime(time, moment().format("HH:mm"))) {
      this.timer = setInterval(this.handleCheckDifference, 5000);
      this.rowMonitoringTimer = setInterval(
        this.handleFirstRowMonitoring,
        2000
      );
    }
  };

  handleStopTimer = () => {
    clearInterval(this.timer);
    this.handleCheckOrderToBeAnnounced();
  };

  handleFirstRowMonitoring = () => {
    const { time } = this.state.row;
    const { interval } = this.state;
    const now = moment()
      .subtract(interval - 1, "m")
      .format("HH:mm");
    const rowTime = time;
    // console.log(rowTime, now);
    if (moment(rowTime, "HH:mm").isBefore(moment(now, "HH:mm"))) {
      clearInterval(this.rowMonitoringTimer);
      this.setState({ isHidden: true });
    }
  };

  handleCheckDifference = () => {
    const { time } = this.props.row;
    const { interval } = this.state;
    const now = moment()
      .add(interval, "m")
      .format("HH:mm");
    const rowTime = time;
    if (moment(now, "HH:mm").isSame(moment(rowTime, "HH:mm"))) {
      console.log("toBeAnnounced ", rowTime);
      this.handleStopTimer();
    }
  };

  handleCheckOrderToBeAnnounced = () => {
    const { orderToAnnounce } = this.props.row;

    switch (orderToAnnounce) {
      case 2:
        this.timer = setInterval(this.handleAnnouncement, 60000);
        break;
      case 3:
        this.timer = setInterval(this.handleAnnouncement, 120000);
        break;
      case 4:
        this.timer = setInterval(this.handleAnnouncement, 180000);
        break;
      default:
        this.timer = setInterval(this.handleAnnouncement, 1000);
        break;
    }
  };

  handleAnnouncement = () => {
    clearInterval(this.timer);
    const { col1 } = this.props.row;
    if (col1) {
      this.setState({ toAnnounce: true }, () => {
        this.props.handleStopFetching(true);
      });
    }
  };

  handleOnStartAnnouncement = e => {
    const { orderToAnnounce } = this.props.row;
    console.log("Announcement start for order number " + orderToAnnounce);

    // if (orderToAnnounce === 1) {
    //   this.props.handleStopFetching(true);
    // }
  };

  handleOnEndAnnouncement = e => {
    const { orderToAnnounce } = this.props.row;
    console.log(
      "Announcement for order number " +
        orderToAnnounce +
        " has finished after " +
        e.elapsedTime +
        " milliseconds"
    );

    // if (orderToAnnounce === 4) {
    //   this.props.handleStartFetching(true);
    // }

    this.setState({ toAnnounce: false }, () => {
      this.props.handleStartFetching(true);
    });
  };

  handleCheckForAnnouncement = row => {
    let res = false;
    const { col1, col2, col3, col4, col5 } = row;

    if (col1) res = true;

    if (col2) res = true;

    if (col3) res = true;

    if (col4) res = true;

    if (col5) res = true;

    return res;
  };

  componentDidMount() {
    this.setState({ row: this.props.row });
    this.handleStartTimer();
  }

  render() {
    const r = this.props.row;
    const { time, side, direction, col1, col2, col3, col4, col5 } = r;
    const isHide = compareTime(time, moment().format("HH:mm"));
    const { isHidden, toAnnounce } = this.state;
    const announcement = () => {
      // if(r.col1)
      if (this.handleCheckForAnnouncement(r)) {
        return (
          <InitSound
            handleOnFinishPlaying={() => {
              announce(
                r,
                this.handleOnStartAnnouncement,
                this.handleOnEndAnnouncement
              );
            }}
          />
        );
      }
    };
    const isAnnounce = () => {
      let res = "";
      if (toAnnounce) {
        res = "is-being-announce";
      }
      return res;
    };
    return (
      <React.Fragment>
        {toAnnounce ? announcement() : <React.Fragment />}
        <tr
          className={`${generateClassNamePerRow(r)} ${
            isHide || isHidden ? "hidden" : ""
          }${isAnnounce()}`}
        >
          <td>{get12hrsValue(time)}</td>
          <td>{side}</td>
          <td>{direction}</td>
          <td>{col1}</td>
          <td>{col2}</td>
          <td>{col3}</td>
          <td>{col4}</td>
          <td>{col5}</td>
        </tr>
      </React.Fragment>
    );
  }
}

export default TableRows;

```

and this the parent component. Table Component

```
import React, { Component } from "react";

import TableHeader from "./TeeTimeHeader";
import TableRows from "./TeeTimeRows";

import axios from "axios";
import moment from "moment";

class Table extends Component {
  componentDidMount() {
    this.handleStartFetching(true);
  }

  handleStopFetching = isStop => {
    if (isStop) {
      clearInterval(this.fetchTimer);
      console.log("fetching stopped ...");
    }
  };

  handleStartFetching = isStart => {
    if (isStart) {
      this.fetchTimer = setInterval(() => {
        axios
          .post("/api/data", {
            date: moment().format("YYYY-MM-DD")
          })
          .then(res => {
            this.props.dispatch({ type: "GET_DATA", payload: res.data });
          });
      }, 10000);
    }
  };

  render() {
    const { rows } = this.props;
    return (
      <div className="table-wrapper">
        <TableHeader />
        <table>
          <thead>
            <tr>
              <th>Time</th>
              <th>Side</th>
              <th />
              <th>COL 1</th>
              <th>COL 2</th>
              <th>COL 3</th>
              <th>COL 4</th>
              <th>COL 5</th>
            </tr>
          </thead>
          <tbody>
            {rows.map((row, i) => {
              return (
                <TableRows
                  row={row}
                  key={i}
                  forMonitoring={true}
                  handleStartFetching={this.handleStartFetching}
                  handleStopFetching={this.handleStopFetching}
                />
              );
            })}
          </tbody>
        </table>
      </div>
    );
  }
}

export default Table;
```

Thank you for helping.

**Comment by tom-s** [comment] 2019-03-10 10:47
Hi. I'm sorry this is way too much code, I don't have time to debug your project. If you can create a reduced test case and live example that shows the issue with speak-tts I'll have a look. In the meantime I'll close this issue.

**Closed as completed by tom-s** 2019-03-10 10:47 UTC

**Comment by cgordon5025** [comment] 2024-05-31 15:53
@jhe01 I am running into the same issue, I set up the voice in init, and after the first reading it will reset to a default voice. Did you have any success here?
